name: Terminally Ambitious
favicon: null
layout_spectrum: 0.7280015023425221
typography_spectrum: 0.000989767024293542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8077102568931878
  lightness: 0.9888465837575495
  saturation: 0.11244050529785454
  rhythmicContrast: 0.32649903604760766
purpose: []
